import { WordPair } from "./gameTypes";

export interface WordCategory {
  id: string;
  name: string;
  pairs: WordPair[];
}

// Conjuntos amplios de pares para cada categoría.
export const WORD_CATEGORIES: WordCategory[] = [
  {
    id: "comida-bebida",
    name: "Comida y bebida",
    pairs: [
      { civil: "Hamburguesa", impostor: "Sandwich", theme: "Rapida" },
      { civil: "Paella", impostor: "Risotto", theme: "Arroces" },
      { civil: "Taco", impostor: "Burrito", theme: "Mexicana" },
      { civil: "Sushi", impostor: "Poke", theme: "Asiatica" },
      { civil: "Ramen", impostor: "Pho", theme: "Sopas" },
      { civil: "Arepa", impostor: "Gordita", theme: "Latino" },
      { civil: "Tamal", impostor: "Hallaca", theme: "Latino" },
      { civil: "Ceviche", impostor: "Cocktail", theme: "Mariscos" },
      { civil: "Croissant", impostor: "Concha", theme: "Panaderia" },
      { civil: "Panqueque", impostor: "Crepa", theme: "Desayuno" },
      { civil: "Chocolate", impostor: "Caramelo", theme: "Dulces" },
      { civil: "Helado", impostor: "Raspado", theme: "Postres" },
      { civil: "Cafe", impostor: "Te", theme: "Bebidas" },
      { civil: "Cerveza", impostor: "Sidra", theme: "Bebidas" },
      { civil: "Vino", impostor: "Champagne", theme: "Bebidas" },
      { civil: "Queso", impostor: "Requeson", theme: "Lacteos" },
      { civil: "Palomitas", impostor: "Nachos", theme: "Snacks" },
      { civil: "Hummus", impostor: "Guacamole", theme: "Dips" },
      { civil: "Falafel", impostor: "Kofta", theme: "Medio Oriente" },
      { civil: "Pizza", impostor: "Focaccia", theme: "Italiana" },
      { civil: "Lasagna", impostor: "Canelones", theme: "Pastas" },
      { civil: "Empanada", impostor: "Samosa", theme: "Rellenos" },
      { civil: "Donut", impostor: "Churro", theme: "Fritos" },
      { civil: "Galleta", impostor: "Brownie", theme: "Postres" },
      { civil: "Yogur", impostor: "Kefir", theme: "Fermentados" },
      { civil: "Smoothie", impostor: "Malteada", theme: "Bebidas" },
      { civil: "Limonada", impostor: "Naranjada", theme: "Refrescos" },
      { civil: "Ensalada", impostor: "Tabule", theme: "Verde" },
      { civil: "Sopa", impostor: "Caldo", theme: "Cuchara" },
      { civil: "Brocheta", impostor: "Anticucho", theme: "Parrilla" },
      { civil: "Curry", impostor: "Masala", theme: "Especias" },
      { civil: "Crema pastelera", impostor: "Merengue", theme: "Reposteria" },
      { civil: "Gazpacho", impostor: "Salmorejo", theme: "Frio" },
    ],
  },
  {
    id: "sistemas-devops",
    name: "Sistemas y DevOps",
    pairs: [
      { civil: "Servidor", impostor: "Mainframe", theme: "Infra" },
      { civil: "Docker", impostor: "Maquina virtual", theme: "Contenedores" },
      { civil: "Balanceador", impostor: "Proxy", theme: "Networking" },
      { civil: "Cache", impostor: "CDN", theme: "Performance" },
      { civil: "Firewall", impostor: "WAF", theme: "Seguridad" },
      { civil: "Kubernetes", impostor: "Nomad", theme: "Orquestacion" },
      { civil: "RabbitMQ", impostor: "Kafka", theme: "Mensajeria" },
      { civil: "API Gateway", impostor: "Service Mesh", theme: "Arquitectura" },
      { civil: "Postgres", impostor: "MySQL", theme: "Base de datos" },
      { civil: "Redis", impostor: "Memcached", theme: "Cache" },
      { civil: "Bash", impostor: "Powershell", theme: "CLI" },
      { civil: "CI/CD", impostor: "Deploy manual", theme: "Release" },
      { civil: "Grafana", impostor: "DataDog", theme: "Observabilidad" },
      { civil: "Logs", impostor: "Traces", theme: "Monitoreo" },
      { civil: "Backup", impostor: "Replica", theme: "Resiliencia" },
      { civil: "IaC", impostor: "Scripts", theme: "Provision" },
      { civil: "Terraform", impostor: "Pulumi", theme: "IaC" },
      { civil: "Ansible", impostor: "Chef", theme: "Configuracion" },
      { civil: "SRE", impostor: "Ops", theme: "Roles" },
      { civil: "SLI", impostor: "SLO", theme: "Confiabilidad" },
      { civil: "Canary", impostor: "Blue green", theme: "Despliegue" },
      { civil: "Feature flag", impostor: "Toggle", theme: "Control" },
      { civil: "Alertas", impostor: "Dashboards", theme: "Observabilidad" },
      { civil: "Cluster", impostor: "Node", theme: "Topologia" },
      { civil: "DNS", impostor: "DHCP", theme: "Red" },
      { civil: "HTTPS", impostor: "TLS", theme: "Cifrado" },
      { civil: "Pipelines", impostor: "Hooks", theme: "Automatizacion" },
      { civil: "Autoscaling", impostor: "Horizontal", theme: "Escala" },
      { civil: "Webhook", impostor: "Polling", theme: "Integracion" },
      { civil: "Chaos", impostor: "Fault injection", theme: "Resiliencia" },
      { civil: "PageRank", impostor: "Load test", theme: "Curiosidades" },
      { civil: "VPN", impostor: "Túnel", theme: "Seguridad" },
    ],
  },
  {
    id: "tecnologia-apps",
    name: "Tecnologia y apps",
    pairs: [
      { civil: "Laptop", impostor: "Tablet", theme: "Dispositivos" },
      { civil: "Smartphone", impostor: "Smartwatch", theme: "Gadgets" },
      { civil: "Bluetooth", impostor: "NFC", theme: "Conectividad" },
      { civil: "Instagram", impostor: "TikTok", theme: "Social" },
      { civil: "Netflix", impostor: "YouTube", theme: "Streaming" },
      { civil: "Spotify", impostor: "Apple Music", theme: "Musica" },
      { civil: "Dropbox", impostor: "Google Drive", theme: "Nube" },
      { civil: "Gmail", impostor: "Outlook", theme: "Correo" },
      { civil: "GPS", impostor: "Brujula", theme: "Navegacion" },
      { civil: "Figma", impostor: "Canva", theme: "Diseno" },
      { civil: "Whatsapp", impostor: "Telegram", theme: "Mensajeria" },
      { civil: "Epub", impostor: "PDF", theme: "Lectura" },
      { civil: "AirDrop", impostor: "Nearby", theme: "Transferencia" },
      { civil: "Blockchain", impostor: "Cripto", theme: "Tendencias" },
      { civil: "Chatbot", impostor: "Livechat", theme: "Soporte" },
      { civil: "VR", impostor: "AR", theme: "Inmersion" },
      { civil: "Router", impostor: "Repeater", theme: "Red" },
      { civil: "5G", impostor: "WiFi 6", theme: "Conectividad" },
      { civil: "Ecommerce", impostor: "Marketplace", theme: "Compras" },
      { civil: "Ride hailing", impostor: "Carsharing", theme: "Movilidad" },
      { civil: "SmartTV", impostor: "Chromecast", theme: "Sala" },
      { civil: "Emulador", impostor: "Simulador", theme: "Software" },
      { civil: "CMS", impostor: "Site builder", theme: "Web" },
      { civil: "SEO", impostor: "SEM", theme: "Marketing" },
      { civil: "Analytics", impostor: "Metrics", theme: "Datos" },
      { civil: "Captcha", impostor: "2FA", theme: "Seguridad" },
      { civil: "Password manager", impostor: "Llave fisica", theme: "Seguridad" },
      { civil: "Data lake", impostor: "Data warehouse", theme: "Datos" },
      { civil: "Edge", impostor: "CDN", theme: "Entrega" },
      { civil: "Streaming", impostor: "Descarga", theme: "Medios" },
      { civil: "Codec", impostor: "Bitrate", theme: "Video" },
      { civil: "Open source", impostor: "Software libre", theme: "Licencias" },
    ],
  },
  {
    id: "deportes",
    name: "Deportes",
    pairs: [
      { civil: "Futbol", impostor: "Rugby", theme: "Equipo" },
      { civil: "Baloncesto", impostor: "Voleibol", theme: "Equipo" },
      { civil: "Tenis", impostor: "Padel", theme: "Raqueta" },
      { civil: "Surf", impostor: "Bodyboard", theme: "Agua" },
      { civil: "Natacion", impostor: "Waterpolo", theme: "Piscina" },
      { civil: "Ciclismo", impostor: "Spinning", theme: "Ruedas" },
      { civil: "Boxeo", impostor: "MMA", theme: "Combate" },
      { civil: "Atletismo", impostor: "Maraton", theme: "Pista" },
      { civil: "Escalada", impostor: "Boulder", theme: "Montana" },
      { civil: "Hockey", impostor: "Beisbol", theme: "Equipo" },
      { civil: "Esgrima", impostor: "Arco", theme: "Precision" },
      { civil: "Golf", impostor: "Minigolf", theme: "Precision" },
      { civil: "Skate", impostor: "BMX", theme: "Urbano" },
      { civil: "Snowboard", impostor: "Esqui", theme: "Nieve" },
      { civil: "Taekwondo", impostor: "Karate", theme: "Artes marciales" },
      { civil: "Judo", impostor: "Aikido", theme: "Artes marciales" },
      { civil: "Cricket", impostor: "Baseball", theme: "Bate" },
      { civil: "Balonmano", impostor: "Futbol sala", theme: "Equipo" },
      { civil: "Remo", impostor: "Kayak", theme: "Agua" },
      { civil: "Triatlon", impostor: "Duotlon", theme: "Resistencia" },
      { civil: "Dardos", impostor: "Billar", theme: "Bar" },
      { civil: "Parkour", impostor: "Gimnasia", theme: "Acrobacia" },
      { civil: "Ajedrez", impostor: "Go", theme: "Mesa" },
      { civil: "Petanca", impostor: "Bochas", theme: "Bolas" },
      { civil: "Softbol", impostor: "Kickball", theme: "Equipo" },
      { civil: "Clavados", impostor: "Natacion sincronizada", theme: "Piscina" },
      { civil: "Montanismo", impostor: "Senderismo", theme: "Aire libre" },
      { civil: "Pesca", impostor: "Submarinismo", theme: "Agua" },
      { civil: "Rally", impostor: "Karting", theme: "Motor" },
      { civil: "Esgrima", impostor: "Kendo", theme: "Armas" },
      { civil: "Esgrima olimpica", impostor: "Savate", theme: "Competencia" },
    ],
  },
  {
    id: "animales",
    name: "Animales",
    pairs: [
      { civil: "Lobo", impostor: "Perro", theme: "Caninos" },
      { civil: "Gato", impostor: "Lince", theme: "Felinos" },
      { civil: "Tigre", impostor: "Jaguar", theme: "Felinos" },
      { civil: "Caballo", impostor: "Cebra", theme: "Equinos" },
      { civil: "Vaca", impostor: "Bison", theme: "Ganado" },
      { civil: "Leon", impostor: "Puma", theme: "Felinos" },
      { civil: "Aguila", impostor: "Halcon", theme: "Aves" },
      { civil: "Buho", impostor: "Lechuza", theme: "Nocturnos" },
      { civil: "Delfin", impostor: "Marsopa", theme: "Marinos" },
      { civil: "Ballena", impostor: "Orca", theme: "Marinos" },
      { civil: "Serpiente", impostor: "Culebra", theme: "Reptiles" },
      { civil: "Cocodrilo", impostor: "Caiman", theme: "Reptiles" },
      { civil: "Rana", impostor: "Sapo", theme: "Anfibios" },
      { civil: "Tortuga", impostor: "Galapago", theme: "Reptiles" },
      { civil: "Gorila", impostor: "Chimpance", theme: "Primates" },
      { civil: "Koala", impostor: "Perezoso", theme: "Mamiferos" },
      { civil: "Hormiga", impostor: "Termita", theme: "Insectos" },
      { civil: "Mariposa", impostor: "Polilla", theme: "Insectos" },
      { civil: "Camello", impostor: "Dromedario", theme: "Desierto" },
      { civil: "Pingüino", impostor: "Alcatraz", theme: "Aves" },
      { civil: "Zorro", impostor: "Coyote", theme: "Canidos" },
      { civil: "Hipopotamo", impostor: "Rinoceronte", theme: "Gigantes" },
      { civil: "Mapache", impostor: "Tejon", theme: "Bosque" },
      { civil: "Castor", impostor: "Nutria", theme: "Rios" },
      { civil: "Flamenco", impostor: "Garza", theme: "Acuaticas" },
      { civil: "Gallo", impostor: "Pavo", theme: "Aves de granja" },
      { civil: "Burro", impostor: "Mulo", theme: "Granja" },
      { civil: "Conejo", impostor: "Liebre", theme: "Roedores" },
      { civil: "Jirafa", impostor: "Okapi", theme: "Savannah" },
      { civil: "Panda", impostor: "Panda rojo", theme: "Osos" },
      { civil: "Caracol", impostor: "Babosa", theme: "Invertebrados" },
      { civil: "Pulpo", impostor: "Calamar", theme: "Marinos" },
    ],
  },
  {
    id: "lugares-viajes",
    name: "Lugares y viajes",
    pairs: [
      { civil: "Playa", impostor: "Bahia", theme: "Vacaciones" },
      { civil: "Montana", impostor: "Canyon", theme: "Naturaleza" },
      { civil: "Ciudad", impostor: "Pueblo", theme: "Urbano" },
      { civil: "Hotel", impostor: "Hostal", theme: "Hospedaje" },
      { civil: "Aeropuerto", impostor: "Estacion", theme: "Transporte" },
      { civil: "Museo", impostor: "Galeria", theme: "Cultura" },
      { civil: "Parque", impostor: "Jardin", theme: "Recreacion" },
      { civil: "Plaza", impostor: "Boulevard", theme: "Ciudad" },
      { civil: "Catarata", impostor: "Geyser", theme: "Agua" },
      { civil: "Glaciar", impostor: "Iceberg", theme: "Nieve" },
      { civil: "Desierto", impostor: "Duna", theme: "Arena" },
      { civil: "Isla", impostor: "Atolon", theme: "Mar" },
      { civil: "Selva", impostor: "Bosque", theme: "Verde" },
      { civil: "Volcan", impostor: "Cráter", theme: "Geologia" },
      { civil: "Templo", impostor: "Catedral", theme: "Religion" },
      { civil: "Mercado", impostor: "Bazar", theme: "Compras" },
      { civil: "Safari", impostor: "Reserva", theme: "Animales" },
      { civil: "Puerto", impostor: "Muelle", theme: "Mar" },
      { civil: "Cueva", impostor: "Gruta", theme: "Subterraneo" },
      { civil: "Ruinas", impostor: "Fuerte", theme: "Historia" },
      { civil: "Rascacielos", impostor: "Torre", theme: "Ciudad" },
      { civil: "Puente", impostor: "Viaducto", theme: "Ingenieria" },
      { civil: "Carretera", impostor: "Autopista", theme: "Viaje" },
      { civil: "Camping", impostor: "Cabaña", theme: "Aire libre" },
      { civil: "Mirador", impostor: "Faro", theme: "Vistas" },
      { civil: "Acuario", impostor: "Zoologico", theme: "Visitas" },
      { civil: "Estadio", impostor: "Arena", theme: "Eventos" },
      { civil: "Teatro", impostor: "Auditorio", theme: "Espectaculos" },
      { civil: "Biblioteca", impostor: "Libreria", theme: "Libros" },
      { civil: "Callejon", impostor: "Avenida", theme: "Calles" },
      { civil: "Cine", impostor: "Autocinema", theme: "Ocio" },
    ],
  },
  {
    id: "profesiones",
    name: "Profesiones",
    pairs: [
      { civil: "Medico", impostor: "Enfermero", theme: "Salud" },
      { civil: "Ingeniero", impostor: "Arquitecto", theme: "Construccion" },
      { civil: "Profesor", impostor: "Tutor", theme: "Educacion" },
      { civil: "Chef", impostor: "Pastelero", theme: "Cocina" },
      { civil: "Piloto", impostor: "Sobrecargo", theme: "Vuelo" },
      { civil: "Bombero", impostor: "Paramedico", theme: "Emergencia" },
      { civil: "Policia", impostor: "Guardia", theme: "Seguridad" },
      { civil: "Abogado", impostor: "Notario", theme: "Derecho" },
      { civil: "Actor", impostor: "Doblador", theme: "Escena" },
      { civil: "Musico", impostor: "DJ", theme: "Arte" },
      { civil: "Periodista", impostor: "Reportero", theme: "Medios" },
      { civil: "Carpintero", impostor: "Ebanista", theme: "Madera" },
      { civil: "Electricista", impostor: "Plomero", theme: "Servicios" },
      { civil: "Disenador", impostor: "Ilustrador", theme: "Creativo" },
      { civil: "Fotografo", impostor: "Camarografo", theme: "Imagen" },
      { civil: "Barbero", impostor: "Estilista", theme: "Imagen" },
      { civil: "Psicologo", impostor: "Coach", theme: "Ayuda" },
      { civil: "Veterinario", impostor: "Zoologo", theme: "Animales" },
      { civil: "Cientifico", impostor: "Investigador", theme: "Laboratorio" },
      { civil: "Astronauta", impostor: "Piloto espacial", theme: "Espacio" },
      { civil: "Analista", impostor: "Consultor", theme: "Empresas" },
      { civil: "Contador", impostor: "Auditor", theme: "Finanzas" },
      { civil: "Panadero", impostor: "Repostero", theme: "Alimentos" },
      { civil: "Mecanico", impostor: "Tecnico", theme: "Taller" },
      { civil: "Jardinero", impostor: "Paisajista", theme: "Plantas" },
      { civil: "Traductor", impostor: "Interprete", theme: "Idiomas" },
      { civil: "Programador", impostor: "Tester", theme: "Software" },
      { civil: "Community manager", impostor: "Influencer", theme: "Redes" },
      { civil: "Product manager", impostor: "Scrum master", theme: "Producto" },
      { civil: "Arqueologo", impostor: "Historiador", theme: "Pasado" },
      { civil: "Investigador forense", impostor: "Criminologo", theme: "Casos" },
      { civil: "Topografo", impostor: "Geografo", theme: "Terreno" },
    ],
  },
  {
    id: "cine-tv",
    name: "Cine y TV",
    pairs: [
      { civil: "Cine", impostor: "Teatro", theme: "Pantalla" },
      { civil: "Documental", impostor: "Reality", theme: "Formatos" },
      { civil: "Sitcom", impostor: "Drama", theme: "Series" },
      { civil: "Animacion", impostor: "Stop motion", theme: "Tecnicas" },
      { civil: "Superheroe", impostor: "Antiheroe", theme: "Personajes" },
      { civil: "Western", impostor: "Noir", theme: "Generos" },
      { civil: "Musical", impostor: "Opera", theme: "Musica" },
      { civil: "Thriller", impostor: "Suspenso", theme: "Tension" },
      { civil: "Comedia", impostor: "Parodia", theme: "Risa" },
      { civil: "Romance", impostor: "Melodrama", theme: "Amor" },
      { civil: "Sci-fi", impostor: "Fantasia", theme: "Imaginacion" },
      { civil: "Cameo", impostor: "Extra", theme: "Roles" },
      { civil: "Guion", impostor: "Storyboard", theme: "Produccion" },
      { civil: "Director", impostor: "Productor", theme: "Equipo" },
      { civil: "Camarografo", impostor: "Sonidista", theme: "Set" },
      { civil: "Festival", impostor: "Premiacion", theme: "Eventos" },
      { civil: "Trailer", impostor: "Teaser", theme: "Promocion" },
      { civil: "Cartelera", impostor: "Streaming", theme: "Distribucion" },
      { civil: "Remake", impostor: "Reboot", theme: "Versiones" },
      { civil: "Saga", impostor: "Spin-off", theme: "Universos" },
      { civil: "Cliffhanger", impostor: "Epilogo", theme: "Narrativa" },
      { civil: "Doblaje", impostor: "Subtitulos", theme: "Idioma" },
      { civil: "Maraton", impostor: "Binge", theme: "Ver" },
      { civil: "Cortometraje", impostor: "Largometraje", theme: "Duracion" },
      { civil: "Stop", impostor: "Recording", theme: "Set" },
      { civil: "Casting", impostor: "Audicion", theme: "Seleccion" },
      { civil: "Trailer", impostor: "Clip", theme: "Anuncio" },
      { civil: "Multicine", impostor: "Autocinema", theme: "Lugar" },
      { civil: "Serie limitada", impostor: "Telenovela", theme: "TV" },
      { civil: "Mini serie", impostor: "Docuserie", theme: "TV" },
      { civil: "Sitcom clasica", impostor: "Mockumentary", theme: "Series" },
      { civil: "Efectos practicos", impostor: "CGI", theme: "FX" },
    ],
  },
  {
    id: "musica-arte",
    name: "Musica y arte",
    pairs: [
      { civil: "Guitarra", impostor: "Ukelele", theme: "Cuerdas" },
      { civil: "Piano", impostor: "Sinte", theme: "Teclas" },
      { civil: "Bateria", impostor: "Cajon", theme: "Percusion" },
      { civil: "Violin", impostor: "Viola", theme: "Cuerdas" },
      { civil: "Saxofon", impostor: "Clarinete", theme: "Viento" },
      { civil: "Opera", impostor: "Opereta", theme: "Escena" },
      { civil: "Reggaeton", impostor: "Trap", theme: "Urbano" },
      { civil: "Rock", impostor: "Metal", theme: "Generos" },
      { civil: "Pop", impostor: "Indie", theme: "Generos" },
      { civil: "Jazz", impostor: "Blues", theme: "Generos" },
      { civil: "Salsa", impostor: "Merengue", theme: "Latino" },
      { civil: "Bachata", impostor: "Cumbia", theme: "Latino" },
      { civil: "Rap", impostor: "Slam", theme: "Voz" },
      { civil: "DJ", impostor: "Productor", theme: "Roles" },
      { civil: "Partitura", impostor: "Tablatura", theme: "Lectura" },
      { civil: "Vinilo", impostor: "Cassette", theme: "Formato" },
      { civil: "Concierto", impostor: "Recital", theme: "Eventos" },
      { civil: "Coral", impostor: "Cuarteto", theme: "Voces" },
      { civil: "Museo", impostor: "Galeria", theme: "Arte" },
      { civil: "Escultura", impostor: "Bajorrelieve", theme: "Volumen" },
      { civil: "Lienzo", impostor: "Mural", theme: "Pintura" },
      { civil: "Acuarela", impostor: "Oleo", theme: "Tecnica" },
      { civil: "Grabado", impostor: "Litografia", theme: "Tecnica" },
      { civil: "Performance", impostor: "Happening", theme: "Accion" },
      { civil: "Graffiti", impostor: "Stencil", theme: "Urbano" },
      { civil: "Ballet", impostor: "Flamenco", theme: "Danza" },
      { civil: "Breakdance", impostor: "Popping", theme: "Danza" },
      { civil: "Dueto", impostor: "Feat", theme: "Colaboracion" },
      { civil: "Coro", impostor: "Solista", theme: "Voces" },
      { civil: "Audifonos", impostor: "Monitores", theme: "Escucha" },
      { civil: "Metronomo", impostor: "Afinador", theme: "Herramientas" },
      { civil: "Festival", impostor: "Jam", theme: "Eventos" },
    ],
  },
  {
    id: "ciencia-espacio",
    name: "Ciencia y espacio",
    pairs: [
      { civil: "Laboratorio", impostor: "Observatorio", theme: "Lugares" },
      { civil: "Microscopio", impostor: "Telescopio", theme: "Instrumentos" },
      { civil: "ADN", impostor: "Proteina", theme: "Biologia" },
      { civil: "Robot", impostor: "Drone", theme: "Futuro" },
      { civil: "Eclipse", impostor: "Equinoccio", theme: "Cielo" },
      { civil: "Astronauta", impostor: "Cosmonauta", theme: "Espacio" },
      { civil: "Quimica", impostor: "Fisica", theme: "Ciencia" },
      { civil: "Gravedad", impostor: "Inercia", theme: "Fuerzas" },
      { civil: "Cohete", impostor: "Sonda", theme: "Exploracion" },
      { civil: "Planeta", impostor: "Asteroide", theme: "Espacio" },
      { civil: "Galaxia", impostor: "Nebulosa", theme: "Universo" },
      { civil: "Meteorito", impostor: "Cometa", theme: "Cielo" },
      { civil: "Vacuna", impostor: "Antibiotico", theme: "Salud" },
      { civil: "Mutacion", impostor: "Evolucion", theme: "Vida" },
      { civil: "Plasma", impostor: "Gas", theme: "Estados" },
      { civil: "Laser", impostor: "Led", theme: "Luz" },
      { civil: "Circuito", impostor: "Chip", theme: "Electronica" },
      { civil: "Algoritmo", impostor: "Heuristica", theme: "Computacion" },
      { civil: "IA", impostor: "Machine learning", theme: "Datos" },
      { civil: "Big Bang", impostor: "Inflacion", theme: "Cosmos" },
      { civil: "Espectro", impostor: "Prisma", theme: "Luz" },
      { civil: "Observatorio", impostor: "Planetario", theme: "Espacio" },
      { civil: "Volcan", impostor: "Geyser", theme: "Tierra" },
      { civil: "Fosil", impostor: "Mineral", theme: "Geologia" },
      { civil: "Erosion", impostor: "Sedimentacion", theme: "Geologia" },
      { civil: "Velocidad luz", impostor: "Velocidad sonido", theme: "Fisica" },
      { civil: "Boson", impostor: "Quark", theme: "Particulas" },
      { civil: "Orbita", impostor: "Traslacion", theme: "Movimiento" },
      { civil: "Holograma", impostor: "Proyeccion", theme: "Imagen" },
      { civil: "Bateria", impostor: "Supercap", theme: "Energia" },
      { civil: "Panel solar", impostor: "Eolica", theme: "Energia" },
      { civil: "Marte", impostor: "Venus", theme: "Planetas" },
    ],
  },
  {
    id: "fiesta-ocio",
    name: "Fiesta y ocio",
    pairs: [
      { civil: "Discoteca", impostor: "Bar", theme: "Noche" },
      { civil: "Karaoke", impostor: "Serenata", theme: "Musica" },
      { civil: "Picnic", impostor: "BBQ", theme: "Comida" },
      { civil: "Casino", impostor: "Bingo", theme: "Juegos" },
      { civil: "Carnaval", impostor: "Feria", theme: "Eventos" },
      { civil: "Festival", impostor: "Concierto", theme: "Musica" },
      { civil: "Spa", impostor: "Sauna", theme: "Relax" },
      { civil: "Patinaje", impostor: "Bolos", theme: "Ocio" },
      { civil: "Escape room", impostor: "Laser tag", theme: "Juegos" },
      { civil: "Brunch", impostor: "Coffee break", theme: "Comida" },
      { civil: "Maraton de series", impostor: "Cine foro", theme: "Pantalla" },
      { civil: "Campamento", impostor: "Retiro", theme: "Aire libre" },
      { civil: "Arcade", impostor: "Consola", theme: "Videojuegos" },
      { civil: "Puzzle", impostor: "Rompecabezas", theme: "Mesa" },
      { civil: "Paintball", impostor: "Gotcha", theme: "Juegos" },
      { civil: "Parrillada", impostor: "Asado", theme: "Comida" },
      { civil: "Tarde de cafe", impostor: "Tea time", theme: "Relax" },
      { civil: "Futbolito", impostor: "Air hockey", theme: "Mesa" },
      { civil: "Merienda", impostor: "Snack time", theme: "Comida" },
      { civil: "Picada", impostor: "Botanas", theme: "Bocados" },
      { civil: "Tarde de juegos", impostor: "Mesa redonda", theme: "Grupo" },
      { civil: "Yoga", impostor: "Pilates", theme: "Bienestar" },
      { civil: "Meditacion", impostor: "Mindfulness", theme: "Bienestar" },
      { civil: "Subasta", impostor: "Trueque", theme: "Juego" },
      { civil: "Feria libros", impostor: "Club lectura", theme: "Cultura" },
      { civil: "Tour gastronomico", impostor: "Cata", theme: "Comida" },
      { civil: "Trivia", impostor: "Quiz", theme: "Preguntas" },
      { civil: "Charla", impostor: "Taller", theme: "Aprender" },
      { civil: "Standup", impostor: "Impro", theme: "Humor" },
      { civil: "Fiesta sorpresa", impostor: "Reunion", theme: "Evento" },
      { civil: "After", impostor: "Precopeo", theme: "Noche" },
      { civil: "Videollamada", impostor: "Chat", theme: "Social" },
    ],
  },
];

const ALL_WORDS: WordPair[] = WORD_CATEGORIES.flatMap(
  (category) => category.pairs,
);

export const WORD_CATEGORY_SUMMARY = WORD_CATEGORIES.map((category) => ({
  id: category.id,
  name: category.name,
  count: category.pairs.length,
}));

export const getCategoryById = (categoryId?: string): WordCategory | undefined =>
  WORD_CATEGORIES.find((category) => category.id === categoryId);

export function getRandomWordPair(categoryId?: string): WordPair {
  const category = getCategoryById(categoryId);
  const pool = category ? category.pairs : ALL_WORDS;
  const index = Math.floor(Math.random() * pool.length);
  return pool[index];
}
